version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - dependencies
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
    groups:
      production-npm:
        dependency-type: production
        update-types:
          - minor
          - patch
      development-npm:
        dependency-type: development
        update-types:
          - minor
          - patch
