pkg:core:
  - changed-files:
      - any-glob-to-any-file: packages/core/**

pkg:server:
  - changed-files:
      - any-glob-to-any-file: packages/server/**

pkg:db:
  - changed-files:
      - any-glob-to-any-file: packages/db/**

pkg:react:
  - changed-files:
      - any-glob-to-any-file: packages/react/**

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
          - "**/*.mdx"
          - apps/docs/**
          - docs/**

area:ci:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**
          - scripts/tegami.mts

area:example:
  - changed-files:
      - any-glob-to-any-file: examples/**

area:tooling:
  - changed-files:
      - any-glob-to-any-file: tooling/**

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - pnpm-lock.yaml
          - .github/dependabot.yml

release:
  - changed-files:
      - any-glob-to-any-file:
          - .tegami/**
          - scripts/tegami.mts
